apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notification-service
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  strategy: {}
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: auth_token
          image: IMAGE_URL/notification-service:latest
          name: notification-service
          resources:
            limits:
              cpu: "250m"
              memory: "1Gi"
            requests:
              cpu: "100m"
              memory: "256Mi"
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: notification-service
  name: notification-service
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 9010
  selector:
    app: notification-service
status:
  loadBalancer: {}